/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_canter_ndkdemo3_JNIMethod */

#ifndef _Included_com_canter_ndkdemo3_JNIMethod
#define _Included_com_canter_ndkdemo3_JNIMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_canter_ndkdemo3_JNIMethod
 * Method:    callStaticMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_canter_ndkdemo3_JNIMethod_callStaticMethod__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_canter_ndkdemo3_JNIMethod
 * Method:    callStaticMethod
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_canter_ndkdemo3_JNIMethod_callStaticMethod__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_canter_ndkdemo3_JNIMethod
 * Method:    callInstanceMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_canter_ndkdemo3_JNIMethod_callInstanceMethod__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_canter_ndkdemo3_JNIMethod
 * Method:    callInstanceMethod
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_canter_ndkdemo3_JNIMethod_callInstanceMethod__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
