/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_canter_ndkdemo2_ndk_JniData */

#ifndef _Included_com_canter_ndkdemo2_ndk_JniData
#define _Included_com_canter_ndkdemo2_ndk_JniData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_canter_ndkdemo2_ndk_JniData
 * Method:    getDataFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_canter_ndkdemo2_ndk_JniData_getDataFromJni
  (JNIEnv *, jclass);

/*
 * Class:     com_canter_ndkdemo2_ndk_JniData
 * Method:    setJavaFromJava
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_canter_ndkdemo2_ndk_JniData_setJavaFromJava
  (JNIEnv *, jclass);

/*
 * Class:     com_canter_ndkdemo2_ndk_JniData
 * Method:    getBitmapFromJni
 * Signature: ()Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_canter_ndkdemo2_ndk_JniData_getBitmapFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
